# Generated by Django 3.2.8 on 2021-10-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anime_From_Users',
            new_name='AnimeFromsUsers',
        ),
        migrations.RenameModel(
            old_name='Anime_List',
            new_name='AnimeList',
        ),
        migrations.RenameModel(
            old_name='Telegram_Users',
            new_name='TelegramUsers',
        ),
    ]
